const projects = [
  {
    title: 'Tonic',
    image: './assets/images/works.svg',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    detailDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias nemo adipisci, harum repudiandae eum mollitia id, blanditiis aut exercitationem expedita veritatis consectetur? Dolor laudantium dignissimos libero, obcaecati minus inventore ratione!',
    company: 'Canopy',
    contribution: 'Back End Dev',
    year: 2005,
    stacks: ['HTML', 'Css', 'Javascript', 'Ruby'],
    liveUrl: '#',
    sourceUrl: '#',
  },
  {
    title: 'Multi-Post <br> Stories',
    image: './assets/images/work2.svg',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    detailDescription: 'more detail',
    company: 'Canopy1',
    contribution: 'Back End Dev1',
    year: 2005,
    stacks: ['HTML', 'Css', 'Javascript'],
    liveUrl: '#',
    sourceUrl: '#',
  },
  {
    title: 'Tonic',
    image: './assets/images/works.svg',
    description: 'test',
    detailDescription: `
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. <br/><br/>
  Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum han printer took a galley of type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it 1960s.`,
    company: 'Canopy',
    contribution: 'Back End Dev',
    year: 2005,
    stacks: ['HTML', 'Css', 'Javascript'],
    liveUrl: '#',
    sourceUrl: '#',
  },
];